// ui/src/components/info.vue
<template>
  <view>
    <!-- 出生时间 -->
    <view class="item">
      <text>
        时间：{{ requestData.year }}年{{ requestData.month }}月{{
          requestData.day
        }}日{{ requestData.hour }}:{{ requestData.minute }}:{{
          requestData.second
        }}
      </text>
    </view>
    <!-- 农历 -->
    <view class="item">
      <text>
        农历：{{ pan.lunar_calendar.year }}年{{ pan.lunar_calendar.month
        }}{{ pan.lunar_calendar.day }} {{ pan.lunar_calendar.time_gan_zhi }}时
      </text>
    </view>
    <!-- 四柱 -->
    <view class="item">
      <text>
        干支：{{ pan.si_zhu.year }}年 {{ pan.si_zhu.month }}月
        {{ pan.si_zhu.day }}日 {{ pan.si_zhu.time }}时
      </text>
    </view>

    <!-- 节气 -->
    <view class="item" style="display: flex">
      <text>节气</text>：
      <view style="display: flex; flex-direction: column">
        <view>
          <text>
            {{ pan.solar_term_first.name }}: {{ pan.solar_term_first.year }}-{{
              pan.solar_term_first.month
            }}-{{ pan.solar_term_first.day }} {{ pan.solar_term_first.hour }}:{{
              pan.solar_term_first.minute
            }}:{{ pan.solar_term_first.second }}
          </text>
        </view>
        <view>
          <text>
            {{ pan.solar_term_second.name }}:
            {{ pan.solar_term_second.year }}-{{
              pan.solar_term_second.month
            }}-{{ pan.solar_term_second.day }}
            {{ pan.solar_term_second.hour }}:{{
              pan.solar_term_second.minute
            }}:{{ pan.solar_term_second.second }}
          </text>
        </view>
      </view>
    </view>

    <!-- 五行局 -->
    <view>
      <text>{{ masculine }}：{{ wuXingNum }}</text>
    </view>
    <!-- 命主、身主、身宫 -->
    <view>
      <text style="margin-right: 20rpx">命主：{{ pan.lord }}</text>
      <text style="margin-right: 20rpx">身主：{{ pan.shen_lord }}</text>
      <text>身宫：{{ pan.shen_gong }}</text>
    </view>
    <!-- 流年 -->
    <view class="item">
      <text>
        流年：{{ requestData.process_year }}年{{
          requestData.process_month
        }}月{{ requestData.process_day }}日{{ requestData.process_hour }}:{{
          requestData.process_minute
        }}:{{ requestData.process_second }}
      </text>
    </view>
    <!-- 大运、小限、斗君 -->
    <view>
      <text style="margin-right: 20rpx">大运：{{ pan.primary_process }} </text>
      <text style="margin-right: 20rpx">小限：{{ pan.second_process }} </text>
      <text>斗君：{{ pan.dou_jun }}</text>
    </view>
  </view>
</template>
<script setup lang="ts">
import type { RequestData, ZiWeiPan } from "@/type";
import { computed } from "vue";

interface InfoProps {
  requestData: RequestData;
  pan: ZiWeiPan;
}
const props = defineProps<InfoProps>();

// 命局阴阳
const masculine = computed(() => {
  let sex = props.requestData.masculine ? "男" : "女";

  let s = ["甲", "丙", "戊", "庚", "壬"].includes(props.pan.si_zhu.year[0])
    ? "阳"
    : "阴";
  return `${s}${sex}`;
});

// 五行局
const wuXingNum = computed(() => {
  switch (props.pan.wu_xing_num) {
    case 2:
      return "水二局";
    case 3:
      return "木三局";
    case 4:
      return "金四局";
    case 5:
      return "土五局";
    default:
      return "火六局";
  }
});
</script>
<style lang="scss" scoped></style>

// ui/src/app/ziwei/info/info.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ZiWei } from 'src/app/interface/response';

@Component({
  selector: 'app-info',
  templateUrl: './info.component.html',
  styleUrls: ['./info.component.scss'],
})
export class InfoComponent implements OnInit {
  @Input()
  pan: ZiWei | null = null;

  get sex(): string | null {
    if (this.pan === null) return null;
    let s0 = this.pan.masculine ? '男' : '女';

    let s = ['甲', '丙', '戊', '庚', '壬'].includes(
      this.pan.native_lunar_calendar.lunar_year[0]
    )
      ? '阳'
      : '阴';
    return `${s}${s0}`;
  }

  // 五行局
  get wuXingNum(): string | null {
    if (this.pan === null) return null;
    switch (this.pan.wu_xing_num) {
      case 2:
        return '水二局';
      case 3:
        return '木三局';
      case 4:
        return '金四局';
      case 5:
        return '土五局';
      default:
        return '火六局';
    }
  }

  constructor() {}

  ngOnInit() {}
}

<div class="content">
  <div *ngIf="pan">
    <div>
      生时：{{ pan.native_date.year }}-{{ pan.native_date.month.toString().padStart(2,'0') }}-{{
      pan.native_date.day.toString().padStart(2,'0') }} {{ pan.native_date.hour.toString().padStart(2,'0') }}:{{
      pan.native_date.minute.toString().padStart(2,'0') }}:{{ pan.native_date.second.toString().padStart(2,'0') }}
    </div>

    <!-- 农历 -->
    <div>
      农历：{{ pan.native_lunar_calendar.lunar_year }}年{{ pan.native_lunar_calendar.lunar_month
      }}{{ pan.native_lunar_calendar.lunar_day }} {{ pan.native_lunar_calendar.time_gan_zhi }}时
    </div>

    <!-- 四柱 -->
    <div style="display: flex">
      干支：
      <div style="display: flex">
        <div style="margin-right: 10px">
          <div> {{ pan.native_lunar_calendar.lunar_year_gan_zhi[0] }}</div>
          <div>{{ pan.native_lunar_calendar.lunar_year_gan_zhi [1]}}</div>
        </div>
        <div style="margin-right: 10px">
          <div>{{ pan.native_lunar_calendar.lunar_month_gan_zhi[0] }}</div>
          <div>{{ pan.native_lunar_calendar.lunar_month_gan_zhi[1] }}</div>
        </div>
        <div style="margin-right: 10px">
          <div> {{ pan.native_lunar_calendar.lunar_day_gan_zhi[0] }} </div>
          <div> {{ pan.native_lunar_calendar.lunar_day_gan_zhi[1] }} </div>
        </div>
        <div>
          <div> {{ pan.native_lunar_calendar.time_gan_zhi[0] }}</div>
          <div> {{ pan.native_lunar_calendar.time_gan_zhi[1] }}</div>
        </div>
      </div>
    </div>

    <!-- 节气 -->
    <div style="display: flex">
      节气：
      <div style="display: flex; flex-direction: column">
        <div>
          {{ pan.native_lunar_calendar. solar_term_first.name }}: {{ pan.native_lunar_calendar.solar_term_first.year
          }}-{{
          pan.native_lunar_calendar.solar_term_first.month
          }}-{{ pan.native_lunar_calendar.solar_term_first.day }} {{ pan.native_lunar_calendar.solar_term_first.hour
          }}:{{
          pan.native_lunar_calendar.solar_term_first.minute
          }}:{{ pan.native_lunar_calendar.solar_term_first.second }}

        </div>
        <div>
          {{ pan.native_lunar_calendar.solar_term_second.name }}:
          {{ pan.native_lunar_calendar.solar_term_second.year }}-{{
          pan.native_lunar_calendar.solar_term_second.month
          }}-{{ pan.native_lunar_calendar.solar_term_second.day }}
          {{ pan.native_lunar_calendar.solar_term_second.hour }}:{{
          pan.native_lunar_calendar.solar_term_second.minute
          }}:{{ pan.native_lunar_calendar.solar_term_second.second }}
        </div>
      </div>
    </div>

    <!-- 五行局 -->
    <div> {{ sex }}：{{ wuXingNum }} </div>

    <!-- 命主、身主、身宫 -->
    <div>
      <label style="margin-right: 20px">命主：{{ pan.lord }}</label>
      <label style="margin-right: 20px">身主：{{ pan.shen_lord }}</label>
      <label>身宫：{{ pan.shen_gong }}</label>
    </div>

    <!-- 流年 -->
    <div>
      流年：{{ pan.process_date.year }}-{{ pan.process_date.month.toString().padStart(2, "0") }}-{{
      pan.process_date.day.toString().padStart(2, "0") }} {{ pan. process_date.hour.toString().padStart(2, "0")}}:{{
      pan.process_date.minute.toString().padStart(2, "0") }}:{{ pan.process_date.second.toString().padStart(2, "0") }}
    </div>

     <!-- 农历 -->
     <div>
      农历：{{ pan.process_lunar_calendar.lunar_year }}年{{ pan.process_lunar_calendar.lunar_month
      }}{{ pan.process_lunar_calendar.lunar_day }} {{ pan.process_lunar_calendar.time_gan_zhi }}时
    </div>

    <!-- 四柱 -->
    <div style="display: flex">
      干支：
      <div style="display: flex">
        <div style="margin-right: 10px">
          <div> {{ pan.process_lunar_calendar.lunar_year_gan_zhi[0] }}</div>
          <div>{{ pan.process_lunar_calendar.lunar_year_gan_zhi [1]}}</div>
        </div>
        <div style="margin-right: 10px">
          <div>{{ pan.process_lunar_calendar.lunar_month_gan_zhi[0] }}</div>
          <div>{{ pan.process_lunar_calendar.lunar_month_gan_zhi[1] }}</div>
        </div>
        <div style="margin-right: 10px">
          <div> {{ pan.process_lunar_calendar.lunar_day_gan_zhi[0] }} </div>
          <div> {{ pan.process_lunar_calendar.lunar_day_gan_zhi[1] }} </div>
        </div>
        <div>
          <div> {{ pan.process_lunar_calendar.time_gan_zhi[0] }}</div>
          <div> {{ pan.process_lunar_calendar.time_gan_zhi[1] }}</div>
        </div>
      </div>
    </div>

    <!-- 大运、小限、斗君 -->
    <div>
      <label style="margin-right: 10px">大运：{{ pan.primary_process }} </label>
      <label style="margin-right: 10px">小限：{{ pan.profection }} </label>
      <label style="margin-right: 10px">流月：{{ pan.liu_month }}</label>
      <label>流日：{{ pan.liu_day }}</label>
    </div>
  </div>
</div>
